# top level stuff you probably don't need to touch
highlighter: pygments
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sfbrigade.github.io/
baseurl: /
title: TrustOSS
author: Trent Oswald (@therebelrobot) <trentoswald@therebelrobot.com>
description: Building trust in Open Source Software and Initiatives for all stakeholders
avatar: trustoss.png
email: trentoswald@therebelrobot.com
github: sfbrigade/trustoss # username
twitter: sfbrigade
linkedin: 
stackoverflow:   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus:
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
